// MetriX Central Mock & Seed Dataset
// District: Ajmer (Directorate of Legal Metrology, Government of Rajasthan)

export const districtInfo = {
  name: "Ajmer",
  state: "Rajasthan",
  zone: "Central Rajasthan Administrative Zone",
  controllerOffice: "Office of the Assistant Controller of Legal Metrology, Ajmer",
  controllerOfficer: {
    name: "Dr. R. K. Sharma",
    designation: "Assistant Controller / District Admin",
    badgeId: "AC-AJM-001",
    email: "ac.ajmer@metrix.gov.in",
    phone: "+91 94140 11001",
    officeAddress: "Collectorate Compound, Kutchery Road, Ajmer, Rajasthan - 305001",
  },
};

export const initialBusinesses = [
  {
    id: "BIZ-AJM-001",
    name: "Shree Balaji Traders",
    applicantName: "Ramesh Kumar",
    gstin: "08AABCS1429B1Z8",
    lmRegNumber: "LM/RAJ/AJM/2022/0488",
    phone: "+91 98290 12345",
    email: "ramesh@balajitraders.in",
    address: "Shop 14, Krishi Mandi Commercial Yard, Kishangarh Road",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305001",
    category: "Wholesale Grain & Agro Trading",
  },
  {
    id: "BIZ-AJM-002",
    name: "Ajmer Grain & Pulse Processing Mills",
    applicantName: "Suresh Chand Sharma",
    gstin: "08AABCA9910C1Z2",
    lmRegNumber: "LM/RAJ/AJM/2021/0192",
    phone: "+91 98291 54321",
    email: "suresh@ajmerpulsemills.com",
    address: "Plot 42-44, Madanganj Industrial Zone, Kishangarh",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305801",
    category: "Food Processing & Milling",
  },
  {
    id: "BIZ-AJM-003",
    name: "Pushkar Commercial Weigh Hub",
    applicantName: "Mahendra Singh Rathore",
    gstin: "08AABCP4412D1Z9",
    lmRegNumber: "LM/RAJ/AJM/2023/0771",
    phone: "+91 94140 88776",
    email: "mahendra@pushkarweigh.in",
    address: "Survey 109, Pushkar Bypass Road, Near Toll Plaza",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305022",
    category: "Heavy Logistics & Public Weighbridge",
  },
  {
    id: "BIZ-AJM-004",
    name: "Rajputana Fuels & Logistics Depot",
    applicantName: "Vikramaditya Singh",
    gstin: "08AABCR7719E1Z4",
    lmRegNumber: "LM/RAJ/AJM/2020/0045",
    phone: "+91 98294 33221",
    email: "logistics@rajputanafuels.com",
    address: "KM Stone 42, NH-48 Beawar Highway",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305202",
    category: "Petroleum & Transport Dispensing",
  },
  {
    id: "BIZ-AJM-005",
    name: "Royal Marble & Heavy Weighbridge Co.",
    applicantName: "Kailash Chand Agarwal",
    gstin: "08AABCR3301F1Z1",
    lmRegNumber: "LM/RAJ/AJM/2021/0812",
    phone: "+91 94142 99001",
    email: "kailash@royalmarbleajmer.com",
    address: "Plot 88, Marble Industrial Area, Kishangarh",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305802",
    category: "Mining & Heavy Stone Processing",
  },
];

export const initialInstruments = [
  {
    id: "INST-AJM-101",
    businessId: "BIZ-AJM-001",
    businessName: "Shree Balaji Traders",
    type: "Electronic Weighing Instrument",
    name: "Commercial Electronic Counter Scale",
    manufacturer: "Essae-Teraoka Ltd",
    model: "DS-215 Precision Counter",
    serialNumber: "SN-983421",
    capacity: "30 kg",
    unit: "kg",
    verificationInterval: "e = 1 g",
    accuracyClass: "Class III (Medium)",
    location: "Counter 1, Main Retail Floor",
    status: "UNDER_REVIEW",
  },
  {
    id: "INST-AJM-102",
    businessId: "BIZ-AJM-002",
    businessName: "Ajmer Grain & Pulse Processing Mills",
    type: "Bulk Grain Hopper Scale",
    name: "Automatic Gravimetric Hopper Weigher",
    manufacturer: "Satake India Engineering",
    model: "SGW-5000 High-Capacity",
    serialNumber: "STK-5T-2023-412",
    capacity: "5,000 kg",
    unit: "kg",
    verificationInterval: "e = 1 kg",
    accuracyClass: "Class III (Medium)",
    location: "Intake Silo Bay 2, Madanganj Mill",
    status: "READY_FOR_ASSIGNMENT",
  },
  {
    id: "INST-AJM-103",
    businessId: "BIZ-AJM-003",
    businessName: "Pushkar Commercial Weigh Hub",
    type: "Heavy Pitless Weighbridge",
    name: "Industrial Pitless Weighbridge (60T)",
    manufacturer: "Avery Weigh-Tronix",
    model: "BridgeMont Pitless 60T",
    serialNumber: "AW-60T-2022-901",
    capacity: "60,000 kg",
    unit: "kg",
    verificationInterval: "e = 10 kg",
    accuracyClass: "Class IV (Heavy)",
    location: "Main Truck Inward Gate, Pushkar Bypass",
    status: "SCHEDULED",
  },
  {
    id: "INST-AJM-104",
    businessId: "BIZ-AJM-004",
    businessName: "Rajputana Fuels & Logistics Depot",
    type: "Dual Liquid Fuel Dispenser",
    name: "Dual Fuel Dispenser (Island A)",
    manufacturer: "Tokheim Quantium",
    model: "510 High-Flow Multi-Product",
    serialNumber: "TK-FUEL-77120",
    capacity: "50 L/min",
    unit: "L/min",
    verificationInterval: "e = 10 mL",
    accuracyClass: "Class 0.5 (Petroleum)",
    location: "Fuel Island 1, Beawar Highway Depot",
    status: "AWAITING_APPROVAL",
  },
  {
    id: "INST-AJM-105",
    businessId: "BIZ-AJM-005",
    businessName: "Royal Marble & Heavy Weighbridge Co.",
    type: "Heavy Pitless Weighbridge",
    name: "Industrial Pitless Weighbridge (100T)",
    manufacturer: "Leotronic Scales Pvt Ltd",
    model: "Hercules Pitless 100T",
    serialNumber: "LEO-100T-2023-88",
    capacity: "100,000 kg",
    unit: "kg",
    verificationInterval: "e = 20 kg",
    accuracyClass: "Class IV (Heavy)",
    location: "Inward Marble Block Yard, Kishangarh",
    status: "AWAITING_APPROVAL",
  },
  {
    id: "INST-AJM-106",
    businessId: "BIZ-AJM-001",
    businessName: "Shree Balaji Traders",
    type: "Platform Scale",
    name: "Heavy Duty Warehouse Platform Scale",
    manufacturer: "Eagle Scales (India)",
    model: "EG-500 Platform",
    serialNumber: "EG-500-2021-309",
    capacity: "500 kg",
    unit: "kg",
    verificationInterval: "e = 50 g",
    accuracyClass: "Class III (Medium)",
    location: "Warehouse Dispatch Dock B",
    status: "CERTIFIED",
  },
  {
    id: "INST-AJM-107",
    businessId: "BIZ-AJM-003",
    businessName: "Pushkar Commercial Weigh Hub",
    type: "Precision Analytical Balance",
    name: "Precision Laboratory Balance",
    manufacturer: "Mettler Toledo",
    model: "XPR205DU DualRange",
    serialNumber: "MT-XPR-441209",
    capacity: "220 g",
    unit: "g",
    verificationInterval: "e = 0.1 mg",
    accuracyClass: "Class I (Special)",
    location: "On-site Quality Calibration Room",
    status: "CERTIFIED",
  },
  {
    id: "INST-AJM-108",
    businessId: "BIZ-AJM-004",
    businessName: "Rajputana Fuels & Logistics Depot",
    type: "Dual Liquid Fuel Dispenser",
    name: "Dual Fuel Dispenser (Island B)",
    manufacturer: "Tokheim Quantium",
    model: "510 High-Flow Multi-Product",
    serialNumber: "TK-FUEL-77121",
    capacity: "50 L/min",
    unit: "L/min",
    verificationInterval: "e = 10 mL",
    accuracyClass: "Class 0.5 (Petroleum)",
    location: "Fuel Island 2, Beawar Highway Depot",
    status: "REJECTED",
  },
  {
    id: "INST-AJM-109",
    businessId: "BIZ-AJM-002",
    businessName: "Ajmer Grain & Pulse Processing Mills",
    type: "Automated Checkweigher",
    name: "High-Speed Bag Checkweigher",
    manufacturer: "Bizerba SE & Co.",
    model: "CWP Neptune High-Speed",
    serialNumber: "BZ-NEP-9034",
    capacity: "6,000 g",
    unit: "g",
    verificationInterval: "e = 1 g",
    accuracyClass: "Class III (Medium)",
    location: "Packaging Line 2, Mill Complex",
    status: "SUBMITTED",
  },
  {
    id: "INST-AJM-110",
    businessId: "BIZ-AJM-005",
    businessName: "Royal Marble & Heavy Weighbridge Co.",
    type: "Industrial Crane Scale",
    name: "Heavy Marble Block Crane Scale",
    manufacturer: "CAS Corporation",
    model: "Caston III Wireless Crane Weigher",
    serialNumber: "CAS-10T-2022-551",
    capacity: "10,000 kg",
    unit: "kg",
    verificationInterval: "e = 2 kg",
    accuracyClass: "Class III (Medium)",
    location: "Gantry Crane Bay 1, Kishangarh",
    status: "SUBMITTED",
  },
];

export const initialLmos = [
  {
    id: "LMO-AJM-021",
    officerId: "LMO-AJM-021",
    name: "Rajesh Kumar",
    designation: "Legal Metrology Officer",
    district: "Ajmer",
    jurisdiction: "Ajmer City & Krishi Mandi Commercial Zone",
    phone: "+91 98290 88123",
    email: "rajesh.kumar@metrix.gov.in",
    activeWorkload: 4,
    pendingInspections: 4,
    completedInspections: 32,
    complianceRate: "98.5%",
    status: "ACTIVE",
  },
  {
    id: "LMO-AJM-014",
    officerId: "LMO-AJM-014",
    name: "Priya Sharma",
    designation: "Legal Metrology Officer",
    district: "Ajmer",
    jurisdiction: "Kishangarh Marble & Industrial Area",
    phone: "+91 98292 77456",
    email: "priya.sharma@metrix.gov.in",
    activeWorkload: 3,
    pendingInspections: 3,
    completedInspections: 41,
    complianceRate: "99.1%",
    status: "ACTIVE",
  },
  {
    id: "LMO-AJM-033",
    officerId: "LMO-AJM-033",
    name: "Vikram Singh",
    designation: "Senior Legal Metrology Officer",
    district: "Ajmer",
    jurisdiction: "Beawar Commercial & Transport Hub",
    phone: "+91 94141 66543",
    email: "vikram.singh@metrix.gov.in",
    activeWorkload: 2,
    pendingInspections: 2,
    completedInspections: 58,
    complianceRate: "97.8%",
    status: "ACTIVE",
  },
  {
    id: "LMO-AJM-008",
    officerId: "LMO-AJM-008",
    name: "Amit Meena",
    designation: "Legal Metrology Officer",
    district: "Ajmer",
    jurisdiction: "Nasirabad & Rural Ajmer Sub-Division",
    phone: "+91 98293 55210",
    email: "amit.meena@metrix.gov.in",
    activeWorkload: 1,
    pendingInspections: 1,
    completedInspections: 26,
    complianceRate: "98.0%",
    status: "ACTIVE",
  },
  {
    id: "LMO-AJM-005",
    officerId: "LMO-AJM-005",
    name: "Sunita Rao",
    designation: "Legal Metrology Officer",
    badgeNumber: "LMO-AJM-005",
    jurisdiction: "Pushkar Rural & Heavy Commercial Scales Zone",
    phone: "+91 94140 56789",
    email: "sunita.rao@lmo.raj.gov.in",
    activeInspectionsCount: 1,
    completedThisMonth: 21,
    complianceRating: "99.4%",
    status: "ON_DUTY",
  },
];

export const initialApplications = [
  {
    id: "APP-2026-00124",
    businessId: "BIZ-AJM-001",
    businessName: "Shree Balaji Traders",
    applicantName: "Ramesh Kumar",
    phone: "+91 98290 12345",
    email: "ramesh@balajitraders.in",
    address: "Shop 14, Krishi Mandi Commercial Yard, Kishangarh Road",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305001",
    instrumentId: "INST-AJM-101",
    instrumentType: "Electronic Weighing Instrument",
    instrumentName: "Commercial Electronic Counter Scale",
    manufacturer: "Essae-Teraoka Ltd",
    model: "DS-215 Precision Counter",
    serialNumber: "SN-983421",
    capacity: "30 kg (e = 1 g)",
    applicationType: "Initial Verification",
    applicationDate: "2026-08-31",
    submissionDate: "2026-08-31",
    status: "UNDER_REVIEW",
    assignedLmoId: null,
    assignedLmoName: "Unassigned",
    scheduledDate: null,
    scheduledTime: null,
    feePaid: "₹ 1,500.00",
    transactionId: "TXN-UPI-AJM-889102",
    documents: [
      { name: "OEM_Model_Approval_Certificate.pdf", size: "2.4 MB", type: "PDF", uploadDate: "2026-08-31" },
      { name: "Purchase_Invoice_TaxReceipt.pdf", size: "1.1 MB", type: "PDF", uploadDate: "2026-08-31" },
      { name: "GST_Establishment_Proof.pdf", size: "850 KB", type: "PDF", uploadDate: "2026-08-31" },
    ],
    photographs: [
      { title: "Serial Plaque & Make", url: "/images/plaque_scale.jpg", uploadDate: "2026-08-31" },
      { title: "Front Display & Platform", url: "/images/front_scale.jpg", uploadDate: "2026-08-31" },
      { title: "Operating Counter Premises", url: "/images/counter_scale.jpg", uploadDate: "2026-08-31" },
    ],
    timeline: [
      { event: "Application Submitted", date: "31 Aug 2026, 09:30 AM", actor: "Ramesh Kumar (Applicant)", note: "Submitted online with all supporting documents." },
      { event: "Document Verification In Progress", date: "31 Aug 2026, 11:00 AM", actor: "Dr. R. K. Sharma (Assistant Controller)", note: "Pending administrative acceptance or rejection." },
    ],
  },
  {
    id: "APP-2026-00125",
    businessId: "BIZ-AJM-002",
    businessName: "Ajmer Grain & Pulse Processing Mills",
    applicantName: "Suresh Chand Sharma",
    phone: "+91 98291 54321",
    email: "suresh@ajmerpulsemills.com",
    address: "Plot 42-44, Madanganj Industrial Zone, Kishangarh",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305801",
    instrumentId: "INST-AJM-102",
    instrumentType: "Bulk Grain Hopper Scale",
    instrumentName: "Automatic Gravimetric Hopper Weigher",
    manufacturer: "Satake India Engineering",
    model: "SGW-5000 High-Capacity",
    serialNumber: "STK-5T-2023-412",
    capacity: "5,000 kg (e = 1 kg)",
    applicationType: "Periodic Re-Verification",
    applicationDate: "2026-08-30",
    submissionDate: "2026-08-30",
    status: "ACCEPTED",
    assignedLmoId: null,
    assignedLmoName: "Ready for Assignment",
    scheduledDate: null,
    scheduledTime: null,
    feePaid: "₹ 4,000.00",
    transactionId: "TXN-NEFT-AJM-440192",
    documents: [
      { name: "Previous_Stamping_Certificate.pdf", size: "1.9 MB", type: "PDF", uploadDate: "2026-08-30" },
      { name: "OEM_Maintenance_Calibration.pdf", size: "1.4 MB", type: "PDF", uploadDate: "2026-08-30" },
    ],
    photographs: [
      { title: "Hopper Scale Structure", url: "/images/hopper_main.jpg", uploadDate: "2026-08-30" },
      { title: "Load Cell Mounting Points", url: "/images/hopper_cells.jpg", uploadDate: "2026-08-30" },
    ],
    timeline: [
      { event: "Application Submitted", date: "30 Aug 2026, 10:15 AM", actor: "Suresh Chand Sharma (Applicant)" },
      { event: "Application Accepted by District Admin", date: "31 Aug 2026, 02:00 PM", actor: "Dr. R. K. Sharma (Assistant Controller)", note: "All mandatory papers valid. Ready for LMO field assignment." },
    ],
  },
  {
    id: "APP-2026-00126",
    businessId: "BIZ-AJM-003",
    businessName: "Pushkar Commercial Weigh Hub",
    applicantName: "Mahendra Singh Rathore",
    phone: "+91 94140 88776",
    email: "mahendra@pushkarweigh.in",
    address: "Survey 109, Pushkar Bypass Road, Near Toll Plaza",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305022",
    instrumentId: "INST-AJM-103",
    instrumentType: "Heavy Pitless Weighbridge",
    instrumentName: "Industrial Pitless Weighbridge (60T)",
    manufacturer: "Avery Weigh-Tronix",
    model: "BridgeMont Pitless 60T",
    serialNumber: "AW-60T-2022-901",
    capacity: "60,000 kg (e = 10 kg)",
    applicationType: "Annual Re-Verification",
    applicationDate: "2026-08-28",
    submissionDate: "2026-08-28",
    status: "SCHEDULED",
    assignedLmoId: "LMO-AJM-021",
    assignedLmoName: "Rajesh Kumar (LMO-AJM-021)",
    scheduledDate: "2026-09-03",
    scheduledTime: "11:30 AM",
    feePaid: "₹ 8,000.00",
    transactionId: "TXN-UPI-AJM-110948",
    documents: [{ name: "Civil_Foundation_Level_Report.pdf", size: "3.1 MB", type: "PDF", uploadDate: "2026-08-28" }],
    photographs: [{ title: "Pitless Weighbridge Deck", url: "/images/weighbridge_deck.jpg", uploadDate: "2026-08-28" }],
    timeline: [
      { event: "Application Submitted", date: "28 Aug 2026, 04:20 PM", actor: "Mahendra Singh Rathore" },
      { event: "Application Accepted", date: "29 Aug 2026, 11:30 AM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "LMO Assigned & Inspection Scheduled", date: "30 Aug 2026, 03:45 PM", actor: "Dr. R. K. Sharma (Assistant Controller)", note: "Assigned to Rajesh Kumar for on-site verification on 03 Sep 2026 at 11:30 AM." },
    ],
  },
  {
    id: "APP-2026-00127",
    businessId: "BIZ-AJM-004",
    businessName: "Rajputana Fuels & Logistics Depot",
    applicantName: "Vikramaditya Singh",
    phone: "+91 98294 33221",
    email: "logistics@rajputanafuels.com",
    address: "KM Stone 42, NH-48 Beawar Highway",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305202",
    instrumentId: "INST-AJM-104",
    instrumentType: "Dual Liquid Fuel Dispenser",
    instrumentName: "Dual Fuel Dispenser (Island A)",
    manufacturer: "Tokheim Quantium",
    model: "510 High-Flow Multi-Product",
    serialNumber: "TK-FUEL-77120",
    capacity: "50 L/min (e = 10 mL)",
    applicationType: "Annual Re-Verification",
    applicationDate: "2026-08-25",
    submissionDate: "2026-08-25",
    status: "AWAITING_APPROVAL",
    assignedLmoId: "LMO-AJM-033",
    assignedLmoName: "Vikram Singh (LMO-AJM-033)",
    scheduledDate: "2026-08-30",
    scheduledTime: "02:30 PM",
    feePaid: "₹ 3,500.00",
    transactionId: "TXN-SBI-AJM-771029",
    documents: [{ name: "Weights_Measures_Prior_Seal.pdf", size: "2.1 MB", type: "PDF", uploadDate: "2026-08-25" }],
    photographs: [
      { title: "Pulsar Totalizer Unit", url: "/images/fuel_pulsar.jpg", uploadDate: "2026-08-30" },
      { title: "Standard 5L Conical Prover Test", url: "/images/5l_prover.jpg", uploadDate: "2026-08-30" },
      { title: "Lead Security Wire Stamped", url: "/images/lead_seal_fuel.jpg", uploadDate: "2026-08-30" },
    ],
    timeline: [
      { event: "Application Submitted", date: "25 Aug 2026, 09:00 AM", actor: "Vikramaditya Singh" },
      { event: "Application Accepted", date: "26 Aug 2026, 10:00 AM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "Inspection Assigned", date: "27 Aug 2026, 02:00 PM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "Physical Inspection Completed in Field", date: "30 Aug 2026, 03:15 PM", actor: "Vikram Singh (LMO-AJM-033)", note: "All 5L & 10L volumetric measurements within MPE. Lead wire seal #SEAL-AJM-2026-4402 applied." },
      { event: "Submitted for Final Sanction", date: "31 Aug 2026, 09:15 AM", actor: "Vikram Singh (LMO-AJM-033)", note: "Awaiting Assistant Controller final certificate sanction." },
    ],
  },
  {
    id: "APP-2026-00128",
    businessId: "BIZ-AJM-005",
    businessName: "Royal Marble & Heavy Weighbridge Co.",
    applicantName: "Kailash Chand Agarwal",
    phone: "+91 94142 99001",
    email: "kailash@royalmarbleajmer.com",
    address: "Plot 88, Marble Industrial Area, Kishangarh",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305802",
    instrumentId: "INST-AJM-105",
    instrumentType: "Heavy Pitless Weighbridge",
    instrumentName: "Industrial Pitless Weighbridge (100T)",
    manufacturer: "Leotronic Scales Pvt Ltd",
    model: "Hercules Pitless 100T",
    serialNumber: "LEO-100T-2023-88",
    capacity: "100,000 kg (e = 20 kg)",
    applicationType: "Initial Verification",
    applicationDate: "2026-08-26",
    submissionDate: "2026-08-26",
    status: "AWAITING_APPROVAL",
    assignedLmoId: "LMO-AJM-014",
    assignedLmoName: "Priya Sharma (LMO-AJM-014)",
    scheduledDate: "2026-08-31",
    scheduledTime: "11:00 AM",
    feePaid: "₹ 12,000.00",
    transactionId: "TXN-HDFC-AJM-991048",
    documents: [{ name: "Civil_Load_Test_Report.pdf", size: "4.5 MB", type: "PDF", uploadDate: "2026-08-26" }],
    photographs: [
      { title: "100T Weighbridge Platform", url: "/images/weighbridge_100t.jpg", uploadDate: "2026-08-31" },
      { title: "Class M1 20T Test Vehicle on Platform", url: "/images/test_lorry.jpg", uploadDate: "2026-08-31" },
      { title: "Junction Box Lead Wire Seal Stamped", url: "/images/jbox_seal.jpg", uploadDate: "2026-08-31" },
    ],
    timeline: [
      { event: "Application Submitted", date: "26 Aug 2026, 11:30 AM", actor: "Kailash Chand Agarwal" },
      { event: "Application Accepted", date: "27 Aug 2026, 04:00 PM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "Inspection Assigned", date: "28 Aug 2026, 10:00 AM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "Physical Inspection Completed in Field", date: "31 Aug 2026, 01:30 PM", actor: "Priya Sharma (LMO-AJM-014)", note: "Eccentricity across 4 corners and span test up to 100,000 kg verified. Seal #SEAL-AJM-2026-8819 affixed." },
      { event: "Submitted for Final Sanction", date: "31 Aug 2026, 04:00 PM", actor: "Priya Sharma (LMO-AJM-014)", note: "Awaiting Assistant Controller final certificate sanction." },
    ],
  },
  {
    id: "APP-2026-00129",
    businessId: "BIZ-AJM-001",
    businessName: "Shree Balaji Traders",
    applicantName: "Ramesh Kumar",
    phone: "+91 98290 12345",
    email: "ramesh@balajitraders.in",
    address: "Shop 14, Krishi Mandi Commercial Yard, Kishangarh Road",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305001",
    instrumentId: "INST-AJM-106",
    instrumentType: "Platform Scale",
    instrumentName: "Heavy Duty Warehouse Platform Scale",
    manufacturer: "Eagle Scales (India)",
    model: "EG-500 Platform",
    serialNumber: "EG-500-2021-309",
    capacity: "500 kg (e = 50 g)",
    applicationType: "Annual Re-Verification",
    applicationDate: "2026-07-10",
    submissionDate: "2026-07-10",
    status: "CERTIFIED",
    assignedLmoId: "LMO-AJM-021",
    assignedLmoName: "Rajesh Kumar (LMO-AJM-021)",
    scheduledDate: "2026-07-15",
    scheduledTime: "10:00 AM",
    feePaid: "₹ 2,000.00",
    transactionId: "TXN-SBI-0091823",
    documents: [{ name: "Platform_Scale_Specs.pdf", size: "1.2 MB", type: "PDF", uploadDate: "2026-07-10" }],
    photographs: [{ title: "Platform Stamped", url: "/images/platform_scale.jpg", uploadDate: "2026-07-15" }],
    timeline: [
      { event: "Application Submitted", date: "10 Jul 2026, 09:00 AM", actor: "Ramesh Kumar" },
      { event: "Application Accepted", date: "11 Jul 2026, 02:00 PM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "Inspection Completed", date: "15 Jul 2026, 11:30 AM", actor: "Rajesh Kumar (LMO)" },
      { event: "Certificate Sanctioned & Issued", date: "16 Jul 2026, 04:00 PM", actor: "Dr. R. K. Sharma (Assistant Controller)", note: "Certificate CERT-2026-00114 generated." },
    ],
  },
  {
    id: "APP-2026-00130",
    businessId: "BIZ-AJM-003",
    businessName: "Pushkar Commercial Weigh Hub",
    applicantName: "Mahendra Singh Rathore",
    phone: "+91 94140 88776",
    email: "mahendra@pushkarweigh.in",
    address: "Survey 109, Pushkar Bypass Road, Near Toll Plaza",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305022",
    instrumentId: "INST-AJM-107",
    instrumentType: "Precision Analytical Balance",
    instrumentName: "Precision Laboratory Balance",
    manufacturer: "Mettler Toledo",
    model: "XPR205DU DualRange",
    serialNumber: "MT-XPR-441209",
    capacity: "220 g (e = 0.1 mg)",
    applicationType: "Initial Verification",
    applicationDate: "2026-06-01",
    submissionDate: "2026-06-01",
    status: "CERTIFIED",
    assignedLmoId: "LMO-AJM-005",
    assignedLmoName: "Sunita Rao",
    scheduledDate: "2026-06-05",
    scheduledTime: "11:00 AM",
    feePaid: "₹ 5,000.00",
    transactionId: "TXN-HDFC-109283",
    documents: [{ name: "Class_I_Calibration_Standard.pdf", size: "3.2 MB", type: "PDF", uploadDate: "2026-06-01" }],
    photographs: [{ title: "Lab Balance Sealed", url: "/images/lab_balance.jpg", uploadDate: "2026-06-05" }],
    timeline: [
      { event: "Application Filed Online", date: "01 Jun 2026, 09:30 AM", actor: "Suresh Chandra Meena" },
      { event: "Document Scrutiny Accepted", date: "02 Jun 2026, 11:00 AM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "LMO Assigned for Field Duty", date: "02 Jun 2026, 11:30 AM", actor: "Dr. R. K. Sharma (Assistant Controller)" },
      { event: "Field Stamping Executed", date: "05 Jun 2026, 01:00 PM", actor: "Sunita Rao (LMO-AJM-005)" },
      { event: "Certificate Sanctioned & Issued", date: "06 Jun 2026, 03:30 PM", actor: "Dr. R. K. Sharma (Assistant Controller)", note: "Certificate CERT-2026-00115 generated." },
    ],
  },
  {
    id: "APP-2026-00131",
    businessId: "BIZ-AJM-004",
    businessName: "Rajputana Fuels & Logistics Depot",
    applicantName: "Vikramaditya Singh",
    phone: "+91 98294 33221",
    email: "logistics@rajputanafuels.com",
    address: "KM Stone 42, NH-48 Beawar Highway",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305202",
    instrumentId: "INST-AJM-108",
    instrumentType: "Dual Liquid Fuel Dispenser",
    instrumentName: "Dual Fuel Dispenser (Island B)",
    manufacturer: "Tokheim Quantium",
    model: "510 High-Flow Multi-Product",
    serialNumber: "TK-FUEL-77121",
    capacity: "50 L/min",
    applicationType: "Re-Verification",
    applicationDate: "2026-08-15",
    submissionDate: "2026-08-15",
    status: "REJECTED",
    assignedLmoId: "LMO-AJM-033",
    assignedLmoName: "Vikram Singh (LMO-AJM-033)",
    rejectionReason: "Pulsar calibration drift exceeded maximum permissible delivery tolerance (+120mL per 10L test). Mechanical service & solenoid valve replacement required.",
    feePaid: "₹ 3,500.00",
    transactionId: "TXN-SBI-440192",
    documents: [{ name: "Fuel_Dispenser_Service_Log.pdf", size: "1.1 MB", type: "PDF", uploadDate: "2026-08-15" }],
    photographs: [{ title: "Dispenser Nozzle Plaque", url: "/images/nozzle.jpg", uploadDate: "2026-08-18" }],
    timeline: [
      { event: "Application Submitted", date: "15 Aug 2026, 09:00 AM", actor: "Vikramaditya Singh" },
      { event: "Inspection Performed", date: "18 Aug 2026, 02:00 PM", actor: "Vikram Singh (LMO-AJM-033)" },
      { event: "Application Rejected by Assistant Controller", date: "19 Aug 2026, 11:30 AM", actor: "Dr. R. K. Sharma (Assistant Controller)", note: "Statutory rejection note dispatched to applicator. Out of stamp." },
    ],
  },
  {
    id: "APP-2026-00132",
    businessId: "BIZ-AJM-002",
    businessName: "Ajmer Grain & Pulse Processing Mills",
    applicantName: "Suresh Chand Sharma",
    phone: "+91 98291 54321",
    email: "suresh@ajmerpulsemills.com",
    address: "Plot 42-44, Madanganj Industrial Zone, Kishangarh",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305801",
    instrumentId: "INST-AJM-109",
    instrumentType: "Automated Checkweigher",
    instrumentName: "High-Speed Bag Checkweigher",
    manufacturer: "Bizerba SE & Co.",
    model: "CWP Neptune High-Speed",
    serialNumber: "BZ-NEP-9034",
    capacity: "6,000 g (e = 1 g)",
    applicationType: "Initial Verification",
    applicationDate: "2026-08-31",
    submissionDate: "2026-08-31",
    status: "SUBMITTED",
    assignedLmoId: null,
    assignedLmoName: "Unassigned",
    scheduledDate: null,
    scheduledTime: null,
    feePaid: "₹ 3,000.00",
    transactionId: "TXN-NEFT-991048",
    documents: [{ name: "Bizerba_Manual.pdf", size: "4.1 MB", type: "PDF", uploadDate: "2026-08-31" }],
    photographs: [{ title: "Checkweigher Conveyor", url: "/images/checkweigher.jpg", uploadDate: "2026-08-31" }],
    timeline: [{ event: "Application Submitted", date: "31 Aug 2026, 05:00 PM", actor: "Suresh Chand Sharma" }],
  },
  {
    id: "APP-2026-00133",
    businessId: "BIZ-AJM-005",
    businessName: "Royal Marble & Heavy Weighbridge Co.",
    applicantName: "Kailash Chand Agarwal",
    phone: "+91 94142 99001",
    email: "kailash@royalmarbleajmer.com",
    address: "Plot 88, Marble Industrial Area, Kishangarh",
    district: "Ajmer",
    state: "Rajasthan",
    pincode: "305802",
    instrumentId: "INST-AJM-110",
    instrumentType: "Industrial Crane Scale",
    instrumentName: "Heavy Marble Block Crane Scale",
    manufacturer: "CAS Corporation",
    model: "Caston III Wireless Crane Weigher",
    serialNumber: "CAS-10T-2022-551",
    capacity: "10,000 kg (e = 2 kg)",
    applicationType: "Periodic Verification",
    applicationDate: "2026-08-31",
    submissionDate: "2026-08-31",
    status: "SUBMITTED",
    assignedLmoId: null,
    assignedLmoName: "Unassigned",
    scheduledDate: null,
    scheduledTime: null,
    feePaid: "₹ 4,500.00",
    transactionId: "TXN-UPI-994102",
    documents: [{ name: "Crane_Hook_Certificate.pdf", size: "1.8 MB", type: "PDF", uploadDate: "2026-08-31" }],
    photographs: [{ title: "Crane Scale Assembly", url: "/images/crane_scale.jpg", uploadDate: "2026-08-31" }],
    timeline: [{ event: "Application Submitted", date: "31 Aug 2026, 06:15 PM", actor: "Kailash Chand Agarwal" }],
  },
];

export const initialInspections = [
  {
    id: "INSP-AJM-2026-0044",
    applicationId: "APP-2026-00128",
    instrumentId: "INST-AJM-105",
    instrumentName: "Industrial Pitless Weighbridge (100T)",
    serialNumber: "LEO-100T-2023-88",
    manufacturer: "Leotronic Scales Pvt Ltd",
    capacity: "100,000 kg (e = 20 kg)",
    ownerName: "Royal Marble & Heavy Weighbridge Co.",
    officer: "Priya Sharma",
    officerId: "LMO-AJM-014",
    officerBadge: "LMO-AJM-014",
    officerRole: "Legal Metrology Officer (Kishangarh Zone)",
    assignedDate: "2026-08-28",
    scheduledDate: "2026-08-31",
    scheduledTime: "11:00 AM",
    inspectionDate: "2026-08-31",
    inspectionTime: "01:30 PM",
    submissionDate: "2026-08-31",
    status: "SUBMITTED_FOR_APPROVAL",
    result: "PASSED",
    location: "Plot 88, Marble Industrial Area, Kishangarh, Ajmer",
    gpsLatitude: "26.5744° N",
    gpsLongitude: "74.8651° E",
    gpsCoords: "26.5744° N, 74.8651° E",
    sealNumber: "SEAL-AJM-2026-8819",
    standardsUsed: "Class M1 20-Tonne Heavy Test Mass Working Standard Lorry #RJ-01-GB-4019",
    checklistItems: [
      { id: "c1", label: "Physical Examination & Maker's Plaque Readability", passed: true },
      { id: "c2", label: "Zero-Load Repeatability & Automatic Return to Zero", passed: true },
      { id: "c3", label: "Corner / Eccentricity Load Testing (4 Corner Load Cells)", passed: true },
      { id: "c4", label: "Maximum Permissible Error (MPE) Verification across range", passed: true },
      { id: "c5", label: "Tamper-Proof Lead/Wire Security Stamping Affixed to Junction Box", passed: true },
    ],
    measurements: [
      { testLoad: "20,000 kg", observed: "20,005 kg", mpe: "± 20 kg", result: "PASS" },
      { testLoad: "50,000 kg", observed: "49,990 kg", mpe: "± 30 kg", result: "PASS" },
      { testLoad: "100,000 kg", observed: "100,015 kg", mpe: "± 40 kg", result: "PASS" },
    ],
    photographs: [
      { title: "100T Weighbridge Platform", url: "/images/weighbridge_100t.jpg", type: "Platform" },
      { title: "Class M1 20T Test Vehicle on Platform", url: "/images/test_lorry.jpg", type: "Test Load" },
      { title: "Junction Box Lead Wire Seal Stamped", url: "/images/jbox_seal.jpg", type: "Security Seal" },
    ],
    officerRemarks: "Full physical and gravimetric verification executed under Schedule VII rules. Eccentricity and span errors well within MPE tolerances. Security wire seal #SEAL-AJM-2026-8819 applied to junction box.",
  },
  {
    id: "INSP-AJM-2026-0048",
    applicationId: "APP-2026-00127",
    instrumentId: "INST-AJM-104",
    instrumentName: "Dual Fuel Dispenser (Island A)",
    serialNumber: "TK-FUEL-77120",
    manufacturer: "Tokheim Quantium",
    capacity: "50 L/min (e = 10 mL)",
    ownerName: "Rajputana Fuels & Logistics Depot",
    officer: "Vikram Singh",
    officerId: "LMO-AJM-033",
    officerBadge: "LMO-AJM-033",
    officerRole: "Senior Legal Metrology Officer (Beawar Zone)",
    assignedDate: "2026-08-27",
    scheduledDate: "2026-08-30",
    scheduledTime: "02:30 PM",
    inspectionDate: "2026-08-30",
    inspectionTime: "03:15 PM",
    submissionDate: "2026-08-31",
    status: "SUBMITTED_FOR_APPROVAL",
    result: "PASSED",
    location: "KM Stone 42, NH-48 Beawar Highway, Ajmer",
    gpsLatitude: "26.1012° N",
    gpsLongitude: "74.3211° E",
    gpsCoords: "26.1012° N, 74.3211° E",
    sealNumber: "SEAL-AJM-2026-4402",
    standardsUsed: "5L & 10L Standard Conical Volumetric Measures (Set #RJ-AJM-09)",
    checklistItems: [
      { id: "c1", label: "Totalizer Mechanical & Electronic Plaque Match", passed: true },
      { id: "c2", label: "Nozzle Anti-Drip Valve Seal Check", passed: true },
      { id: "c3", label: "Standard 5L Conical Proving Measure Test", passed: true },
      { id: "c4", label: "Standard 10L Volumetric Delivery Error Test", passed: true },
      { id: "c5", label: "Pulsar Unit Lead Wire Security Stamping", passed: true },
    ],
    measurements: [
      { testLoad: "5.000 L", observed: "5.002 L", mpe: "± 0.025 L", result: "PASS" },
      { testLoad: "10.000 L", observed: "9.998 L", mpe: "± 0.050 L", result: "PASS" },
    ],
    photographs: [
      { title: "Pulsar Totalizer Unit", url: "/images/fuel_pulsar.jpg", type: "Plaque" },
      { title: "Standard 5L Conical Prover Test", url: "/images/5l_prover.jpg", type: "Volumetric Test" },
      { title: "Lead Security Wire Stamped", url: "/images/lead_seal_fuel.jpg", type: "Security Seal" },
    ],
    officerRemarks: "Volumetric error at 10L delivery was -2 mL (well within statutory permissible ±50 mL). Security wire stamped on calibration pulsar.",
  },
  {
    id: "INSP-AJM-2026-0038",
    applicationId: "APP-2026-00129",
    instrumentId: "INST-AJM-106",
    instrumentName: "Heavy Duty Warehouse Platform Scale",
    serialNumber: "EG-500-2021-309",
    manufacturer: "Eagle Scales (India)",
    capacity: "500 kg (e = 50 g)",
    ownerName: "Shree Balaji Traders",
    officer: "Rajesh Kumar",
    officerId: "LMO-AJM-021",
    officerBadge: "LMO-AJM-021",
    officerRole: "Legal Metrology Officer (Ajmer City)",
    assignedDate: "2026-07-11",
    scheduledDate: "2026-07-15",
    scheduledTime: "10:00 AM",
    inspectionDate: "2026-07-15",
    inspectionTime: "11:30 AM",
    submissionDate: "2026-07-15",
    status: "APPROVED",
    result: "PASSED",
    certificateNumber: "CERT-2026-00114",
    location: "Shop 14, Krishi Mandi Commercial Yard, Kishangarh Road, Ajmer",
    gpsLatitude: "26.4499° N",
    gpsLongitude: "74.6399° E",
    gpsCoords: "26.4499° N, 74.6399° E",
    sealNumber: "SEAL-AJM-2026-1104",
    standardsUsed: "Class M1 500kg Test Weights Set",
    checklistItems: [
      { id: "c1", label: "Physical Examination & Plaque Readability", passed: true },
      { id: "c2", label: "Zero-Load Repeatability & Return to Zero", passed: true },
      { id: "c3", label: "Corner Load Eccentricity Test", passed: true },
      { id: "c4", label: "Maximum Permissible Error (MPE) Verification", passed: true },
      { id: "c5", label: "Security Seal Affixed", passed: true },
    ],
    measurements: [
      { testLoad: "100 kg", observed: "100.02 kg", mpe: "± 0.05 kg", result: "PASS" },
      { testLoad: "250 kg", observed: "249.98 kg", mpe: "± 0.10 kg", result: "PASS" },
      { testLoad: "500 kg", observed: "500.04 kg", mpe: "± 0.15 kg", result: "PASS" },
    ],
    photographs: [{ title: "Platform Stamped", url: "/images/platform_scale.jpg", type: "Security Seal" }],
    officerRemarks: "Platform scale verified and sealed. Approved by Assistant Controller Dr. R. K. Sharma.",
  },
  {
    id: "INSP-AJM-2026-0039",
    applicationId: "APP-2026-00130",
    instrumentId: "INST-AJM-107",
    instrumentName: "Precision Laboratory Balance",
    serialNumber: "MT-XPR-441209",
    manufacturer: "Mettler Toledo",
    capacity: "220 g (e = 0.1 mg)",
    ownerName: "Pushkar Commercial Weigh Hub",
    officer: "Sunita Rao",
    officerId: "LMO-AJM-005",
    officerBadge: "LMO-AJM-005",
    officerRole: "Legal Metrology Officer",
    assignedDate: "2026-06-02",
    scheduledDate: "2026-06-05",
    scheduledTime: "11:00 AM",
    inspectionDate: "2026-06-05",
    inspectionTime: "01:00 PM",
    submissionDate: "2026-06-05",
    status: "APPROVED",
    result: "PASSED",
    certificateNumber: "CERT-2026-00115",
    location: "Survey 109, Pushkar Bypass Road, Near Toll Plaza, Ajmer",
    gpsLatitude: "26.4901° N",
    gpsLongitude: "74.5502° E",
    gpsCoords: "26.4901° N, 74.5502° E",
    sealNumber: "SEAL-GOV-RAJ-99418",
    standardsUsed: "Class E2 Standard Analytical Test Masses",
    checklistItems: [
      { id: "c1", label: "Environmental Temperature & Draft Shield Integrity", passed: true },
      { id: "c2", label: "Internal Calibration Weight Verification", passed: true },
      { id: "c3", label: "Class E2 Standard Test Masses Repeatability", passed: true },
      { id: "c4", label: "Linearity across 10 discrete measurement steps", passed: true },
      { id: "c5", label: "Affixing Official Holographic QR Security Seal", passed: true },
    ],
    measurements: [
      { testLoad: "10.0000 g", observed: "10.00002 g", mpe: "± 0.0002 g", result: "PASS" },
      { testLoad: "100.0000 g", observed: "100.00008 g", mpe: "± 0.0005 g", result: "PASS" },
      { testLoad: "200.0000 g", observed: "200.00012 g", mpe: "± 0.0010 g", result: "PASS" },
    ],
    photographs: [{ title: "Lab Balance Sealed", url: "/images/lab_balance.jpg", type: "Holographic Seal" }],
    officerRemarks: "Certified under Class I special specifications. Approved by Assistant Controller.",
  },
];

export const initialCertificates = [
  {
    id: "CERT-2026-00114",
    certificateNumber: "CERT-2026-00114",
    officialNumber: "LM/RAJ/AJM/2026/00114/STAT",
    instrumentId: "INST-AJM-106",
    instrumentName: "Heavy Duty Warehouse Platform Scale",
    instrumentType: "Platform Scale",
    serialNumber: "EG-500-2021-309",
    manufacturer: "Eagle Scales (India)",
    model: "EG-500 Platform",
    capacity: "500 kg (e = 50 g)",
    ownerName: "Shree Balaji Traders",
    businessAddress: "Shop 14, Krishi Mandi Commercial Yard, Kishangarh Road, Ajmer - 305001",
    verificationDate: "2026-07-15",
    validFrom: "2026-07-15",
    validUntil: "2027-07-14",
    verificationResult: "PASSED & STAMPED",
    status: "VALID",
    verifyingOfficer: "Rajesh Kumar (LMO-AJM-021)",
    approvingOfficer: "Dr. R. K. Sharma (Assistant Controller)",
    district: "Ajmer",
    issuingAuthority: "Directorate of Legal Metrology, Government of Rajasthan",
    sealNumber: "SEAL-AJM-2026-1104",
    securityHash: "0x8fa921c4e772b109dc6312a09f81a7b3c2e1f4d5",
    verificationToken: "CERT-2026-00114",
    verificationUrl: "http://localhost:3000/verify/CERT-2026-00114",
  },
  {
    id: "CERT-2026-00115",
    certificateNumber: "CERT-2026-00115",
    officialNumber: "LM/RAJ/AJM/2026/00115/PREC",
    instrumentId: "INST-AJM-107",
    instrumentName: "Precision Laboratory Balance",
    instrumentType: "Precision Analytical Balance",
    serialNumber: "MT-XPR-441209",
    manufacturer: "Mettler Toledo",
    model: "XPR205DU DualRange",
    capacity: "220 g (e = 0.1 mg)",
    ownerName: "Pushkar Commercial Weigh Hub",
    businessAddress: "Survey 109, Pushkar Bypass Road, Near Toll Plaza, Ajmer - 305022",
    verificationDate: "2026-06-05",
    validFrom: "2026-06-05",
    validUntil: "2027-06-04",
    verificationResult: "PASSED & STAMPED",
    status: "VALID",
    verifyingOfficer: "Sunita Rao (LMO-AJM-005)",
    approvingOfficer: "Dr. R. K. Sharma (Assistant Controller)",
    district: "Ajmer",
    issuingAuthority: "Directorate of Legal Metrology, Government of Rajasthan",
    sealNumber: "SEAL-GOV-RAJ-99418",
    securityHash: "0x11be983427acfa88921b776a394fe98c44a2b109",
    verificationToken: "CERT-2026-00115",
    verificationUrl: "http://localhost:3000/verify/CERT-2026-00115",
  },
  {
    id: "CERT-2025-00091",
    certificateNumber: "CERT-2025-00091",
    officialNumber: "LM/RAJ/AJM/2025/00091/WB",
    instrumentId: "INST-AJM-103",
    instrumentName: "Industrial Pitless Weighbridge (60T)",
    instrumentType: "Heavy Pitless Weighbridge",
    serialNumber: "AW-60T-2022-901",
    manufacturer: "Avery Weigh-Tronix",
    model: "BridgeMont Pitless 60T",
    capacity: "60,000 kg (e = 10 kg)",
    ownerName: "Pushkar Commercial Weigh Hub",
    businessAddress: "Survey 109, Pushkar Bypass Road, Near Toll Plaza, Ajmer - 305022",
    verificationDate: "2025-09-02",
    validFrom: "2025-09-02",
    validUntil: "2026-09-01",
    verificationResult: "PASSED & STAMPED",
    status: "EXPIRING_SOON",
    verifyingOfficer: "Rajesh Kumar (LMO-AJM-021)",
    approvingOfficer: "Dr. R. K. Sharma (Assistant Controller)",
    district: "Ajmer",
    issuingAuthority: "Directorate of Legal Metrology, Government of Rajasthan",
    sealNumber: "SEAL-AJM-2025-5591",
    securityHash: "0xaa908234ef192b8471cd64a38910bc49281aef12",
    verificationToken: "CERT-2025-00091",
    verificationUrl: "http://localhost:3000/verify/CERT-2025-00091",
  },
  {
    id: "CERT-2025-00042",
    certificateNumber: "CERT-2025-00042",
    officialNumber: "LM/RAJ/AJM/2025/00042/AUTO",
    instrumentId: "INST-AJM-109",
    instrumentName: "High-Speed Bag Checkweigher",
    instrumentType: "Automated Checkweigher",
    serialNumber: "BZ-NEP-9034",
    manufacturer: "Bizerba SE & Co.",
    model: "CWP Neptune High-Speed",
    capacity: "6,000 g (e = 1 g)",
    ownerName: "Ajmer Grain & Pulse Processing Mills",
    businessAddress: "Plot 42-44, Madanganj Industrial Zone, Kishangarh, Ajmer - 305801",
    verificationDate: "2025-08-10",
    validFrom: "2025-08-10",
    validUntil: "2026-08-09",
    verificationResult: "EXPIRED",
    status: "EXPIRED",
    verifyingOfficer: "Priya Sharma (LMO-AJM-014)",
    approvingOfficer: "Dr. R. K. Sharma (Assistant Controller)",
    district: "Ajmer",
    issuingAuthority: "Directorate of Legal Metrology, Government of Rajasthan",
    sealNumber: "SEAL-AJM-2025-3382",
    securityHash: "0x33cf891244ab9102ef89c102a984bc1938abef41",
    verificationToken: "CERT-2025-00042",
    verificationUrl: "http://localhost:3000/verify/CERT-2025-00042",
  },
  {
    id: "CERT-2025-00018",
    certificateNumber: "CERT-2025-00018",
    officialNumber: "LM/RAJ/AJM/2025/00018/CRANE",
    instrumentId: "INST-AJM-110",
    instrumentName: "Heavy Marble Block Crane Scale",
    instrumentType: "Industrial Crane Scale",
    serialNumber: "CAS-10T-2022-551",
    manufacturer: "CAS Corporation",
    model: "Caston III Wireless Crane Weigher",
    capacity: "10,000 kg (e = 2 kg)",
    ownerName: "Royal Marble & Heavy Weighbridge Co.",
    businessAddress: "Plot 88, Marble Industrial Area, Kishangarh, Ajmer - 305802",
    verificationDate: "2025-08-25",
    validFrom: "2025-08-25",
    validUntil: "2026-08-24",
    verificationResult: "REVOKED",
    status: "REVOKED",
    verifyingOfficer: "Priya Sharma (LMO-AJM-014)",
    approvingOfficer: "Dr. R. K. Sharma (Assistant Controller)",
    district: "Ajmer",
    issuingAuthority: "Directorate of Legal Metrology, Government of Rajasthan",
    sealNumber: "SEAL-AJM-2025-9901",
    securityHash: "0x44ab771928cf1092a837bc9102df49102837bc81",
    verificationToken: "CERT-2025-00018",
    verificationUrl: "http://localhost:3000/verify/CERT-2025-00018",
  },
];

export const initialNotifications = [
  {
    id: "NOTIF-AJM-001",
    title: "Application APP-2026-00124 has been submitted.",
    message: "Shree Balaji Traders submitted Initial Verification for Electronic Weighing Instrument (SN-983421).",
    category: "APPLICATION_SUBMITTED",
    timestamp: "2026-08-31T09:30:00Z",
    unread: true,
    actionUrl: "/applications",
    priority: "HIGH",
  },
  {
    id: "NOTIF-AJM-002",
    title: "Inspection APP-2026-00128 has been completed by LMO Priya Sharma.",
    message: "Physical verification completed for Royal Marble Weighbridge (100T). Awaiting your final certificate approval.",
    category: "INSPECTION_SUBMITTED",
    timestamp: "2026-08-31T16:00:00Z",
    unread: true,
    actionUrl: "/admin/awaiting-certificates",
    priority: "HIGH",
  },
  {
    id: "NOTIF-AJM-003",
    title: "Certificate CERT-2026-00127 is awaiting final approval.",
    message: "LMO Vikram Singh submitted field test results for Dual Fuel Dispenser (Island A) at Rajputana Fuels.",
    category: "AWAITING_APPROVAL",
    timestamp: "2026-08-31T15:15:00Z",
    unread: true,
    actionUrl: "/admin/awaiting-certificates",
    priority: "HIGH",
  },
  {
    id: "NOTIF-AJM-004",
    title: "Certificate CERT-2025-00091 will expire soon.",
    message: "60T Weighbridge at Pushkar Commercial Weigh Hub expires in 1 day (01 Sep 2026). Re-verification scheduled.",
    category: "EXPIRY_WARNING",
    timestamp: "2026-08-30T10:00:00Z",
    unread: false,
    actionUrl: "/certificates",
    priority: "MEDIUM",
  },
];

export const initialAuditLogs = [
  {
    id: "AUD-AJM-101",
    actor: "Ramesh Kumar (Applicant)",
    action: "APPLICATION_SUBMITTED",
    entity: "Application",
    entityId: "APP-2026-00124",
    timestamp: "2026-08-31T09:30:00Z",
    metadata: { businessName: "Shree Balaji Traders", instrument: "Electronic Counter Scale" },
  },
  {
    id: "AUD-AJM-102",
    actor: "Dr. R. K. Sharma (Assistant Controller)",
    action: "APPLICATION_ACCEPTED",
    entity: "Application",
    entityId: "APP-2026-00125",
    timestamp: "2026-08-31T14:00:00Z",
    metadata: { businessName: "Ajmer Grain & Pulse Mills", status: "READY_FOR_ASSIGNMENT" },
  },
  {
    id: "AUD-AJM-103",
    actor: "Dr. R. K. Sharma (Assistant Controller)",
    action: "LMO_ASSIGNED",
    entity: "Verification Assignment",
    entityId: "APP-2026-00126",
    timestamp: "2026-08-30T15:45:00Z",
    metadata: { assignedOfficer: "Rajesh Kumar (LMO-AJM-021)", scheduledDate: "2026-09-03" },
  },
  {
    id: "AUD-AJM-104",
    actor: "Priya Sharma (LMO-AJM-014)",
    action: "INSPECTION_SUBMITTED",
    entity: "Inspection",
    entityId: "INSP-AJM-2026-0044",
    timestamp: "2026-08-31T16:00:00Z",
    metadata: { result: "PASSED", sealNumber: "SEAL-AJM-2026-8819", instrument: "Weighbridge 100T" },
  },
  {
    id: "AUD-AJM-105",
    actor: "Dr. R. K. Sharma (Assistant Controller)",
    action: "APPROVAL_GRANTED",
    entity: "Certificate",
    entityId: "CERT-2026-00114",
    timestamp: "2026-07-16T16:00:00Z",
    metadata: { certificateNumber: "CERT-2026-00114", business: "Shree Balaji Traders" },
  },
];
