export const initialUserProfile = {
  businessName: "Apex Logistics & Retail Hub Pvt. Ltd.",
  tradeName: "Apex MegaMart",
  regNumber: "DL-LM-REG-2024-0982",
  gstin: "07AAACA1234A1Z5",
  contactPerson: "Sahil Kumar",
  email: "compliance@apexlogistics.in",
  phone: "+91 98765 43210",
  address: "Plot 42, Okhla Industrial Area Phase III",
  district: "South Delhi",
  state: "Delhi",
  pincode: "110020",
  role: "business", // 'business' | 'lmo' | 'admin'
};

export const initialInstruments = [
  {
    id: "INST-2024-001",
    name: "Electronic Retail Counter Scale",
    category: "Non-Automatic Weighing Instrument",
    accuracyClass: "Class III",
    manufacturer: "Essae-Teraoka Ltd.",
    model: "DS-252 Electronic Price Computing",
    serialNumber: "ES-2023-88219",
    maxCapacity: "30 kg",
    minCapacity: "100 g",
    verificationScaleInterval: "5 g",
    location: "Counter 04, Okhla Supercenter, Delhi",
    installationDate: "2023-11-15",
    verificationStatus: "VERIFIED",
    lastVerificationDate: "2025-08-20",
    validUntil: "2026-08-19",
    certificateId: "LM-DEL-2025-00481",
    stampingOfficer: "Inspector Rajesh Sharma (LMO-104)",
  },
  {
    id: "INST-2024-002",
    name: "Industrial Pitless Weighbridge",
    category: "Automatic / Heavy Weighbridge",
    accuracyClass: "Class IV",
    manufacturer: "Avery Weigh-Tronix",
    model: "BridgeMont Pitless 60T",
    serialNumber: "AW-60T-2022-901",
    maxCapacity: "60,000 kg (60 Ton)",
    minCapacity: "400 kg",
    verificationScaleInterval: "10 kg",
    location: "Gate 2 Inward Logistics Bay, Okhla",
    installationDate: "2022-04-10",
    verificationStatus: "EXPIRING_SOON",
    lastVerificationDate: "2025-09-02",
    validUntil: "2026-09-01",
    certificateId: "LM-DEL-2025-00892",
    stampingOfficer: "Officer P. K. Verma (LMO-102)",
  },
  {
    id: "INST-2024-003",
    name: "Precision Analytical Micro-Balance",
    category: "Precision Laboratory Balance",
    accuracyClass: "Class I (Special)",
    manufacturer: "Mettler Toledo",
    model: "XPR205DU DualRange",
    serialNumber: "MT-XPR-441209",
    maxCapacity: "220 g",
    minCapacity: "1 mg",
    verificationScaleInterval: "0.1 mg",
    location: "Quality Assurance Lab, Bay 3",
    installationDate: "2024-01-20",
    verificationStatus: "VERIFIED",
    lastVerificationDate: "2026-01-15",
    validUntil: "2027-01-14",
    certificateId: "LM-DEL-2026-00114",
    stampingOfficer: "Dr. Sunita Rao (GATC Lead)",
  },
  {
    id: "INST-2024-004",
    name: "High-Speed Dual Fuel Dispenser",
    category: "Liquid Fuel Measuring Instrument",
    accuracyClass: "Accuracy Class 0.5",
    manufacturer: "Tokheim Corporation",
    model: "Quantium 510 Multi-Product",
    serialNumber: "TK-DUO-2023-774",
    maxCapacity: "80 L/min",
    minCapacity: "5 L/min",
    verificationScaleInterval: "0.01 L",
    location: "Internal Fleet Fueling Island A",
    installationDate: "2023-06-12",
    verificationStatus: "UNDER_VERIFICATION",
    lastVerificationDate: "2025-07-28",
    validUntil: "2026-07-27",
    certificateId: "LM-DEL-2025-00311",
    stampingOfficer: "Inspector Rajesh Sharma (LMO-104)",
  },
  {
    id: "INST-2024-005",
    name: "Heavy Duty Platform Scale",
    category: "Non-Automatic Weighing Instrument",
    accuracyClass: "Class III",
    manufacturer: "Eagle Weighing Systems",
    model: "EGW-500 Heavy Platform",
    serialNumber: "EG-500-2021-309",
    maxCapacity: "500 kg",
    minCapacity: "2 kg",
    verificationScaleInterval: "50 g",
    location: "Dispatch Loading Dock B",
    installationDate: "2021-08-01",
    verificationStatus: "EXPIRED",
    lastVerificationDate: "2025-06-10",
    validUntil: "2026-06-09",
    certificateId: "LM-DEL-2025-00109",
    stampingOfficer: "Officer P. K. Verma (LMO-102)",
  },
  {
    id: "INST-2024-006",
    name: "Automated Checkweigher Conveyor",
    category: "Automatic Gravimetric Filling Instrument",
    accuracyClass: "Class XIII(1)",
    manufacturer: "Bizerba SE & Co. KG",
    model: "CWP Neptune High-Speed",
    serialNumber: "BZ-NEP-9034",
    maxCapacity: "6,000 g",
    minCapacity: "50 g",
    verificationScaleInterval: "1 g",
    location: "Packaging Line 2, Warehouse 1",
    installationDate: "2024-03-01",
    verificationStatus: "VERIFIED",
    lastVerificationDate: "2026-03-10",
    validUntil: "2027-03-09",
    certificateId: "LM-DEL-2026-00445",
    stampingOfficer: "Inspector Rajesh Sharma (LMO-104)",
  }
];

export const initialApplications = [
  {
    id: "APP-2026-00192",
    instrumentId: "INST-2024-002",
    instrumentName: "Industrial Pitless Weighbridge (60T)",
    serialNumber: "AW-60T-2022-901",
    applicationType: "Periodic Re-Verification",
    status: "SCHEDULED",
    submissionDate: "2026-08-18",
    scheduledDate: "2026-08-28",
    scheduledTime: "11:30 AM",
    assignedOfficer: "Inspector Rajesh Sharma (LMO-104)",
    location: "Gate 2 Inward Logistics Bay, Okhla, Delhi",
    feePaid: "₹ 4,500.00",
    transactionId: "TXN-SBI-993821049",
    documents: [
      { name: "Manufacturer_Test_Report.pdf", size: "2.4 MB" },
      { name: "Previous_Verification_Certificate.pdf", size: "1.1 MB" },
      { name: "Installation_Calibration_Log.pdf", size: "890 KB" }
    ],
    notes: "Mandatory annual statutory re-verification for heavy commercial trade operations.",
  },
  {
    id: "APP-2026-00195",
    instrumentId: "INST-2024-004",
    instrumentName: "High-Speed Dual Fuel Dispenser",
    serialNumber: "TK-DUO-2023-774",
    applicationType: "Periodic Re-Verification",
    status: "UNDER_VERIFICATION",
    submissionDate: "2026-08-20",
    scheduledDate: "2026-08-26",
    scheduledTime: "02:00 PM",
    assignedOfficer: "Inspector Rajesh Sharma (LMO-104)",
    location: "Internal Fleet Fueling Island A",
    feePaid: "₹ 3,200.00",
    transactionId: "TXN-HDFC-441209382",
    documents: [
      { name: "Nozzle_Calibration_Certificate.pdf", size: "1.8 MB" }
    ],
    notes: "Field volumetric displacement test scheduled for standard delivery nozzles.",
  },
  {
    id: "APP-2026-00188",
    instrumentId: "INST-2024-005",
    instrumentName: "Heavy Duty Platform Scale (500kg)",
    serialNumber: "EG-500-2021-309",
    applicationType: "Re-Verification (Post-Expiry)",
    status: "UNDER_REVIEW",
    submissionDate: "2026-08-24",
    scheduledDate: "Pending Assignment",
    scheduledTime: "-",
    assignedOfficer: "Pending Assignment",
    location: "Dispatch Loading Dock B",
    feePaid: "₹ 2,800.00",
    transactionId: "TXN-UPI-8821094821",
    documents: [
      { name: "Service_Rectification_Invoice.pdf", size: "950 KB" }
    ],
    notes: "Load cell recalibrated after minor drift observed during routine facility checks.",
  },
  {
    id: "APP-2026-00174",
    instrumentId: "INST-2024-003",
    instrumentName: "Precision Analytical Micro-Balance",
    serialNumber: "MT-XPR-441209",
    applicationType: "Initial Verification",
    status: "PASSED",
    submissionDate: "2026-01-08",
    scheduledDate: "2026-01-15",
    scheduledTime: "10:00 AM",
    assignedOfficer: "Dr. Sunita Rao (GATC Lead)",
    location: "Quality Assurance Lab, Bay 3",
    feePaid: "₹ 5,000.00",
    transactionId: "TXN-SBI-10928374",
    documents: [
      { name: "OEM_Class_I_Standard.pdf", size: "3.2 MB" }
    ],
    notes: "Approved and certified under Legal Metrology General Rules 2011 Schedule VII.",
  }
];

export const initialCertificates = [
  {
    id: "LM-DEL-2026-00114",
    certificateNumber: "LM/DL/2026/00114/PREC",
    instrumentId: "INST-2024-003",
    instrumentName: "Precision Analytical Micro-Balance",
    serialNumber: "MT-XPR-441209",
    manufacturer: "Mettler Toledo",
    model: "XPR205DU DualRange",
    capacity: "220 g (e = 0.1 mg)",
    ownerName: "Apex Logistics & Retail Hub Pvt. Ltd.",
    location: "Quality Assurance Lab, Bay 3, Okhla, Delhi",
    issueDate: "2026-01-15",
    validFrom: "2026-01-15",
    validUntil: "2027-01-14",
    status: "VALID",
    issuingAuthority: "Directorate of Legal Metrology, Govt. of NCT of Delhi",
    officerName: "Dr. Sunita Rao",
    officerDesignation: "Authorized Government Metrology Specialist",
    securityHash: "0x8fa921c4e772b109dc6312a09f81",
    sealNumber: "SEAL-GOV-DEL-99418",
    verificationStandardsUsed: "NPL Class E2 Standard Analytical Weights (Set #409)",
  },
  {
    id: "LM-DEL-2026-00445",
    certificateNumber: "LM/DL/2026/00445/AUTO",
    instrumentId: "INST-2024-006",
    instrumentName: "Automated Checkweigher Conveyor",
    serialNumber: "BZ-NEP-9034",
    manufacturer: "Bizerba SE & Co. KG",
    model: "CWP Neptune High-Speed",
    capacity: "6,000 g (e = 1 g)",
    ownerName: "Apex Logistics & Retail Hub Pvt. Ltd.",
    location: "Packaging Line 2, Warehouse 1",
    issueDate: "2026-03-10",
    validFrom: "2026-03-10",
    validUntil: "2027-03-09",
    status: "VALID",
    issuingAuthority: "Department of Consumer Affairs & Legal Metrology, Delhi",
    officerName: "Inspector Rajesh Sharma",
    officerDesignation: "Legal Metrology Officer (Zone South)",
    securityHash: "0x44cd891b0028a3f9e217d84a51bb",
    sealNumber: "SEAL-GOV-DEL-77102",
    verificationStandardsUsed: "OIML R51 Working Standards (F1 Grade)",
  },
  {
    id: "LM-DEL-2025-00481",
    certificateNumber: "LM/DL/2025/00481/NAWI",
    instrumentId: "INST-2024-001",
    instrumentName: "Electronic Retail Counter Scale",
    serialNumber: "ES-2023-88219",
    manufacturer: "Essae-Teraoka Ltd.",
    model: "DS-252 Electronic Price Computing",
    capacity: "30 kg (e = 5 g)",
    ownerName: "Apex Logistics & Retail Hub Pvt. Ltd.",
    location: "Counter 04, Okhla Supercenter, Delhi",
    issueDate: "2025-08-20",
    validFrom: "2025-08-20",
    validUntil: "2026-08-19",
    status: "VALID",
    issuingAuthority: "Legal Metrology Department, Government of Delhi",
    officerName: "Inspector Rajesh Sharma",
    officerDesignation: "Legal Metrology Officer (Zone South)",
    securityHash: "0x11be983427acfa88921b776a394f",
    sealNumber: "SEAL-GOV-DEL-33829",
    verificationStandardsUsed: "Class M1 Cast Iron Working Standards (20kg Set)",
  },
  {
    id: "LM-DEL-2025-00892",
    certificateNumber: "LM/DL/2025/00892/WB",
    instrumentId: "INST-2024-002",
    instrumentName: "Industrial Pitless Weighbridge",
    serialNumber: "AW-60T-2022-901",
    manufacturer: "Avery Weigh-Tronix",
    model: "BridgeMont Pitless 60T",
    capacity: "60,000 kg (e = 10 kg)",
    ownerName: "Apex Logistics & Retail Hub Pvt. Ltd.",
    location: "Gate 2 Inward Logistics Bay, Okhla",
    issueDate: "2025-09-02",
    validFrom: "2025-09-02",
    validUntil: "2026-09-01",
    status: "EXPIRING_SOON",
    issuingAuthority: "Legal Metrology Department, Government of Delhi",
    officerName: "Officer P. K. Verma",
    officerDesignation: "Senior Legal Metrology Officer",
    securityHash: "0xaa908234ef192b8471cd64a38910",
    sealNumber: "SEAL-GOV-DEL-55912",
    verificationStandardsUsed: "Mobile Heavy Verification Vehicle (20T Test Masses)",
  }
];

export const initialInspections = [
  {
    id: "INSP-2026-0044",
    applicationId: "APP-2026-00192",
    instrumentId: "INST-2024-002",
    instrumentName: "Industrial Pitless Weighbridge (60T)",
    officer: "Inspector Rajesh Sharma",
    officerRole: "Legal Metrology Officer (LMO-104)",
    scheduledDate: "2026-08-28",
    scheduledTime: "11:30 AM",
    status: "SCHEDULED",
    location: "Gate 2 Inward Logistics Bay, Okhla, Delhi",
    gpsCoords: "28.5284° N, 77.2798° E",
    checklistItems: [
      { id: "c1", label: "Physical Examination & Plaque Readability", passed: true },
      { id: "c2", label: "Zero-Load Repeatability & Return to Zero", passed: true },
      { id: "c3", label: "Corner / Eccentricity Load Testing", passed: true },
      { id: "c4", label: "Maximum Permissible Error (MPE) Verification", passed: false },
      { id: "c5", label: "Tamper-Proof Lead/Wire Security Stamping", passed: false }
    ],
    measurements: [
      { testLoad: "10,000 kg", observed: "10,002 kg", mpe: "± 10 kg", result: "PASS" },
      { testLoad: "30,000 kg", observed: "29,995 kg", mpe: "± 15 kg", result: "PASS" },
      { testLoad: "60,000 kg", observed: "60,010 kg", mpe: "± 20 kg", result: "PASS" }
    ],
    remarks: "Weighbridge platform leveled and pit free of debris. Ready for physical standard load vehicle tests."
  },
  {
    id: "INSP-2026-0038",
    applicationId: "APP-2026-00174",
    instrumentId: "INST-2024-003",
    instrumentName: "Precision Analytical Micro-Balance",
    officer: "Dr. Sunita Rao",
    officerRole: "Lead Metrology Scientist (GATC)",
    scheduledDate: "2026-01-15",
    scheduledTime: "10:00 AM",
    status: "COMPLETED",
    location: "Quality Assurance Lab, Bay 3",
    gpsCoords: "28.5301° N, 77.2785° E",
    checklistItems: [
      { id: "c1", label: "Environmental Temperature & Draft Shield Integrity", passed: true },
      { id: "c2", label: "Internal Calibration Weight Verification", passed: true },
      { id: "c3", label: "Class E2 Standard Test Masses Repeatability", passed: true },
      { id: "c4", label: "Linearity across 10 discrete measurement steps", passed: true },
      { id: "c5", label: "Affixing Official Holographic QR Security Seal", passed: true }
    ],
    measurements: [
      { testLoad: "10.0000 g", observed: "10.00002 g", mpe: "± 0.0002 g", result: "PASS" },
      { testLoad: "100.0000 g", observed: "100.00008 g", mpe: "± 0.0005 g", result: "PASS" },
      { testLoad: "200.0000 g", observed: "200.00012 g", mpe: "± 0.0010 g", result: "PASS" }
    ],
    remarks: "Certified for analytical testing under Class I specifications. Holographic seal #SEAL-GOV-DEL-99418 applied."
  }
];

export const initialNotifications = [
  {
    id: "NOTIF-101",
    title: "Certificate Expiring in 6 Days",
    message: "Certificate LM-DEL-2025-00892 for Weighbridge (60T) expires on 01 Sep 2026. Please complete re-verification.",
    category: "EXPIRY_WARNING",
    timestamp: "2026-08-25T14:30:00Z",
    unread: true,
    actionUrl: "/applications/apply?instrumentId=INST-2024-002",
    actionText: "Apply Re-Verification",
    priority: "HIGH"
  },
  {
    id: "NOTIF-102",
    title: "Inspection Scheduled by Department",
    message: "Application APP-2026-00192 has been scheduled for inspection on 28 Aug 2026 at 11:30 AM by Inspector Rajesh Sharma.",
    category: "SCHEDULE_UPDATE",
    timestamp: "2026-08-24T09:15:00Z",
    unread: true,
    actionUrl: "/applications",
    actionText: "View Schedule",
    priority: "MEDIUM"
  },
  {
    id: "NOTIF-103",
    title: "Digital Certificate Issued",
    message: "Certificate LM-DEL-2026-00445 has been generated for Automated Checkweigher. Digitally signed and QR verified.",
    category: "CERTIFICATE_ISSUED",
    timestamp: "2026-08-20T16:45:00Z",
    unread: false,
    actionUrl: "/certificates",
    actionText: "Download Certificate",
    priority: "LOW"
  }
];
