// MetriX Central Status Constants and State Machine Definitions

export const APPLICATION_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  REJECTED: "REJECTED",
  ACCEPTED: "ACCEPTED",
  SCHEDULED: "SCHEDULED",
  UNDER_VERIFICATION: "UNDER_VERIFICATION",
  VERIFICATION_COMPLETED: "VERIFICATION_COMPLETED",
  AWAITING_APPROVAL: "AWAITING_APPROVAL",
  APPROVED: "APPROVED",
  CERTIFIED: "CERTIFIED",
};

export const INSPECTION_STATUS = {
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  SUBMITTED: "SUBMITTED",
  RETURNED: "RETURNED",
  APPROVED: "APPROVED",
};

export const CERTIFICATE_STATUS = {
  VALID: "VALID",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
};
